FROM microfocusidolserver/nifi-ver2-minimal:25.2

# Copy custom NiFi properties
COPY ./nifi.properties /opt/nifi/nifi-current/conf/nifi.properties

# Copy persistent NiFi directories from prepared host folders
COPY ./nifi-persistent-volumes/conf/ /opt/nifi/nifi-current/conf/
COPY ./nifi-persistent-volumes/content_repository/ /opt/nifi/nifi-current/content_repository/
COPY ./nifi-persistent-volumes/database_repository/ /opt/nifi/nifi-current/database_repository/
COPY ./nifi-persistent-volumes/flowfile_repository/ /opt/nifi/nifi-current/flowfile_repository/
COPY ./nifi-persistent-volumes/provenance_repository/ /opt/nifi/nifi-current/provenance_repository/
