apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: omnigroupserver-config
    files:
      - omnigroupserver.cfg
  - name: omnigroupserver-aes
    files:
      - aes.key
