# Main LLM model for IDOL AnswerBank integration
# Generated on Thu Jun 25 09:29:05 IDT 2026
IDOL_LLM_MAIN_MODEL_NAME="gemma-4-e4b:latest"
IDOL_LLM_MAIN_MODEL_PATH="/home/kduser3/llm-models/gemma-4-e4b:latest.gguf"
