# Main LLM model for IDOL AnswerBank integration
# Generated on Mon Jul 27 12:02:34 IDT 2026
IDOL_LLM_MAIN_MODEL_NAME="gemma-4-e4b:latest"
IDOL_LLM_MAIN_MODEL_PATH="/home/kduser6/llm-models/gemma-4-e4b:latest.gguf"
