# Main LLM model for IDOL AnswerBank integration
# Generated on Sun Aug 30 23:00:11 IDT 2026
IDOL_LLM_MAIN_MODEL_NAME="gemma-4-e4b:latest"
IDOL_LLM_MAIN_MODEL_PATH="/home/kduser6/llm-models/gemma-4-e4b:latest.gguf"
