apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: nifi-basic-flow
    files:
      - basic.xml
  - name: nifi-basic-ssl-flow
    files:
      - basic.ssl.xml
  - name: nifi-mmap-flow
    files:
      - with.mmap.xml
  - name: nifi-mmap-ssl-flow
    files:
      - with.mmap.ssl.xml